spring.application.name=backend

# 1. ??i c?ng t? 6543 thành 5432 và thêm tham s? options ? cu?i URL
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require&prepareThreshold=0&options=-c%20search_path%3Dpublic

# 2. ??t Username quay v? thu?n 'postgres' nh? ban ??u
spring.datasource.username=${MY_DB_USER}
spring.datasource.password=${MY_DB_PASS}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true