spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
# Dùng cấu trúc ${TÊN_BIẾN} để làm đại diện
spring.datasource.username=${MY_DB_USER}
spring.datasource.password=${MY_DB_PASS}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
